- util/secrules/securityruleset.go
- util/secrules/securityruleset_test.go
> contrast security group rules that point to consistent

- util/stringutils/stringutils.go
- utils/utils.go
- utils/utils_test.go
修正：utils.TruncateString和stringutils.Interface2String逻辑不正确
> fix: truncatestring and interface2string

- util/filterclause/filterclause.go
- utils/misc.go
fix: 
1. parse sqlconnection with query params
2. filterclause support isnullorempty call
> fix: 1. parse sqlconnection with query params 2. isnullorempty filerclause

- util/filterclause/filterclause.go
修正：filterclause没做params的越界检查，导致panic
> fix: filterclause check out of range params access

- util/netutils/errors.go
- util/netutils/netutils.go
修正：1. IPV4Prefix bug fix 2. 支持 errors
/cc @Zexi @yousong
> fix: netutils misc bugfix, prefix support contains operation

- util/secrules/secruleset_test.go
> secrules: 添加空规则列表测试

- errors/errors.go
add const error and error wrap for unified error handling
> feature: add const error and error wrap for unified error handling

- tristate/tristate.go
> tristate: 添加NewFromBool(bool)方法

- util/errors/http_error.go
- util/prometheus/gin_handler.go
> Replace gopkg.in/gin-gonic/gin.v1 with github.com/gin-gonic/gin

- util/regutils/regutils.go
匹配金额支持正负号
/cc @swordqiu @yousong
> fix currency reg

- util/regutils/regutils.go
- util/regutils/regutils_test.go
/cc @swordqiu 
/cc @ioito 
/cc @Zexi
> regutils: 改进域名校验

- errors/aggregate.go
- errors/aggregate_test.go
- util/version/version.go
- util/version/version_test.go
1. 把util/errors中处理聚合错误的代码挪到errors，以后错误处理统一用yunion.io/x/pkg/errors处理
2. version包含short datetime
> fix: 1. move util/errors/aggegrate to errors 2. version add short date string

- util/regutils/regutils.go
- util/regutils/regutils_test.go
- util/timeutils/timeutils.go
- util/timeutils/timeutils_test.go
修正：full iso time format支持变长的subsecond
> fix: full iso time format支持变长的subSecond

- util/netutils/netutils.go
*修复netutils equals 报错
/cc @swordqiu @zhasm
> netutils equals bugfix

- util/secrules/secrules.go
> optimized: 导出GetPorts函数

- errors/consts.go
> feature: add errors consts

- errors/aggregate.go
- errors/aggregate_test.go
- errors/consts.go
改进：实现aggregate错误的Cause方法
/cc @zexi @yousong
> feature: implement cause of aggregate error

- util/timeutils/timeutils.go
- util/timeutils/timeutils_test.go
> fix: 支持匹配google cloud时间格式

- gotypes/deepcopy.go
- util/reflectutils/jsonfield.go
```
reflectutils: ignore fields properly
gotypes: add constraint notes for DeepCopy
````
/cc @swordqiu
> reflectutils: ignore fields properly

- util/reflectutils/jsonfield.go
添加了FieldInfoCache之后，无论是往外传struct还是指针，
都没有对SStructFieldInfo中的Tags （一个map）进行deepcopy。
而这个map甚至整个SStructFieldInfo是readonly的。所以整个
SStructFieldInfo都应该deepcopy一份出来。
> fix: Fix the bug in case of adding FieldInfoCache

- util/netutils/netutils.go
- utils/misc_test.go
> netutils: fix build with golang version 1.12 and earlier

- util/reflectutils/jsonfield.go
- util/reflectutils/jsonfield_test.go
- utils/fibonacci_retrier_test.go
Fixes 3532215789 ("Add StructFieldInfo Cache with FieldInfo's Copy")
/cc @rainzm @swordqiu
> reflectutils: jsonfield: fix MarshalName()

- util/reflectutils/reflectutils.go
- util/reflectutils/reflectutils_test.go
修正：FindAnonymousStructPoint重构，检查严格一些，加了单元测试
> fix: FindAnonymousStructPoint recode

- util/signalutils/dumpstack_others.go
- util/signalutils/dumpstack_windows.go
Already merged in yunionio/onecloud#5260
/cc @swordqiu
> signalutils: add platform specific SetDumpStackSignal()

- util/reflectutils/jsonfield.go
- util/reflectutils/jsonfield_test.go
> feature: get struct fields with duplicate json name

- util/reflectutils/jsonfield.go
- util/reflectutils/jsonfield_test.go
> feature: make ParseFieldJsonInfo method standalone

- util/reflectutils/jsonfield.go
- util/reflectutils/jsonfield_test.go
允许struct嵌入的匿名struct的field tag覆盖内部field的tag
/cc @zexi @yousong @wanyaoqi
> feature: allow struct anonymous struct field tags to override internal tags

- errors/errors.go
> add errors.Errorf

- util/reflectutils/jsonfield.go
- util/reflectutils/jsonfield_test.go
修正：json name匹配的方法改回和以前兼容
/cc @zexi
> fix: json name match rule backward compatble

- prettytable/prettytable.go
- prettytable/termwidth_unix.go
- prettytable/termwidth_windows.go
修正：prettytable windows兼容
/cc @yousong
> fix: make windows compatible

- prettytable/termwidth_windows.go
> feature: windows termWidth

- gotypes/gotypes.go
- util/reflectutils/jsonfield.go
改进：1. 提供方法获取struct中所有的字段的json信息，即使该字段设置为ignore 
修正：1. gotypes SetValue和SetSlice的bug
> fix: 1. allow get all fields including ignored fields 2. fix set string bug

- prettytable/prettytable.go
> new pretty table with try term width

- util/timeutils/timeutils.go
- util/timeutils/timeutils_test.go
- utils/utils_test.go
增加：ParseTimeStrInTimeZone方法
/cc @zexi @yousong
> feature: add ParseTimeStrInTimeZone

- util/reflectutils/ambiguous.go
- util/reflectutils/jsonfield_test.go
> fix TAG_PREFIX invalid syntax

- util/compare/compare.go
- util/compare/compare_test.go
fix: 避免删除本地external_id为空的资源
/cc @zexi @swordqiu
> fix: 避免删除本地external_id为空的资源

- util/netutils/netutils.go
> fix: set private prefixes

- util/netutils/netutils.go
修正：private prefixes列表可能没有被初始化
/cc @zexi
> fix: private prefxies may not initialized

- util/compare/compare.go
- util/compare/compare_test.go
> fix(pkg): avoid duplicated resource

- utils/fibonacci_retrier.go
- utils/fibonacci_retrier_test.go
> FibonacciRetrier: start with context

- util/regutils/regutils.go
- util/regutils/regutils_test.go
- util/timeutils/timeutils.go
- util/timeutils/timeutils_test.go
> fix: support time string of sqlite

- util/regutils/regutils.go
- util/regutils/regutils_test.go
- util/timeutils/timeutils.go
- util/timeutils/timeutils_test.go
fix: support clickhosue time format 2022-06-01 00:00:00 +0000 UTC
> fix: support clickhosue time format 2022-06-01 00:00:00 +0000 UTC

- util/reflectutils/jsonfield.go
- util/reflectutils/jsonfield_test.go
Add parent SEmbedStructFieldValue in SStructFieldValue, default is not set
field, if we want alloct embeded struct, just call Field.Set(Value).
Signed-off-by: wanyaoqi <d3lx.yq@gmail.com>
> fix: fetch embeded struct field without allocate

- util/httputils/httputils.go
> fix(httputils): add some withRetry case

- utils/misc.go
- utils/misc_test.go
> fix: password contains @

- util/fileutils/filesize.go
- util/streamutils/streamutils.go
- util/streamutils/streamutils_test.go
fix: streamutils error for zero sized input
> fix: streamutils error for zero sized input

- util/stringutils/stringutils.go
- util/stringutils/stringutils_test.go
> fix: bytes to hex string
